### ISSUE TITLE
channel-thread passes undefined formatSender to channel-message, crashing render

### ISSUE THREAD

**Issue by mdproctor** [casehubio/blocks-ui#73]
## Problem

`channel-thread.ts` line 15 declares `formatSender` as optional with no default:

```ts
@property({ attribute: false }) formatSender?: (sender: string, actorType: ActorType) => string;
```

Lines 73 and 93 pass `.formatSender=${this.formatSender}` to `channel-message`. When no parent sets `formatSender` on the thread (the common case — channel-feed doesn't), this passes `undefined`, which overwrites `channel-message`'s default `(s) => s`.

Result: `TypeError: this.formatSender is not a function` — message content never renders.

Introduced by commit ab98ee7 (fix #66).

## Fix

Give `channel-thread.formatSender` the same default as `channel-message`:

```ts
@property({ attribute: false }) formatSender: (sender: string, actorType: ActorType) => string = (s) => s;
```

Or conditionally pass it in the template:

```ts
.formatSender=${this.formatSender ?? ((s: string) => s)}
```

## Impact

All messages inside threads render blank — only sender names and thread counts visible.
